export const KEYWORD_CONFIG: Record<string, string> = {
  'car-on-rent': 'Car on rent',
  'car-hire': 'Car hire',
  'rent-a-vehicle': 'Rent a vehicle',
  'online-car-booking': 'Online car booking',
  'rent-vehicle-online': 'Rent vehicle online',
  'car-rental-platform': 'Car rental platform',
  'vehicle-booking-platform': 'Vehicle booking platform',
  'affordable-car-rental': 'Affordable car rental',
  'cheap-car-rental': 'Cheap car rental',
  'best-car-rental': 'Best car rental',
  'low-cost-car-rental': 'Low cost car rental',
  'car-rental-deals': 'Car rental deals',
  'car-rental-prices': 'Car rental prices',
  'daily-car-rental': 'Daily car rental',
  'short-term-car-rental': 'Short term car rental',
  'long-term-car-rental': 'Long term car rental',
  'hourly-car-rental': 'Hourly car rental',
  'reliable-car-rental': 'Reliable car rental',
  'trusted-car-rental': 'Trusted car rental',
  'verified-car-rental': 'Verified car rental',
  'best-car-rental-service': 'Best car rental service',
  'top-car-rental-company': 'Top car rental company',
  'instant-car-booking': 'Instant car booking',
  'quick-car-booking': 'Quick car booking',
  'car-rental-near-me': 'Car rental near me',
  'rent-car-now': 'Rent car now',
  'travel-car-rental': 'Travel car rental',
  'tour-car-rental': 'Tour car rental',
  'family-car-rental': 'Family car rental',
  'business-car-rental': 'Business car rental',
  'car-rental-with-driver': 'Car rental with driver',
  'car-rental-without-driver': 'Car rental without driver',
  'car-rental-marketplace': 'Car rental marketplace',
  'vehicle-rental-marketplace': 'Vehicle rental marketplace',
  'personal-car-rental': 'Personal car rental',
  'commercial-car-rental': 'Commercial car rental',
  'airport-transfer': 'Airport transfer',
  'self-drive-car-rental': 'Self drive car rental',
  'wedding-car-rental': 'Wedding car rental',
  'airport-transfer-services': 'Airport transfer services',
  'monthly-daily-car-rental': 'Monthly & daily car rental',
  'luxury-economy-budget-cars': 'Luxury, economy & budget cars',
  'bus-coaster-rental': 'Bus & coaster rental',
  'tour-travel-vehicles': 'Tour & travel vehicles',
}


